### ISSUE TITLE
statusBar.frame.size.height is zero

### ISSUE THREAD

**Issue by ndlinh** [CosmicMind/Material#957] opened 2017-11-04 03:41 UTC
In iOS 9, `statusBar.frame.size.height` is zero. This caused statusbar overlap toolbar in ToolbarController.

I think the code to set height in StatusBarController should be like this:

        if #available(iOS 11, *) {
            let v = topLayoutGuide.length
            statusBar.frame.size.height = 0 < v ? v : 20
        } else {
            statusBar.frame.size.height = 20
        }

**Comment by OrkhanAlikhanov** [comment] 2017-11-04 06:28
@danieldahan I guess @ndlinh is right. I was suspicious about the commit https://github.com/CosmicMind/Material/commit/ea0e0027b20ec19244f391f95b812839fcb55799 when I see it.

**Comment by danieldahan** [comment] 2017-11-07 15:39
Looks correct, I will double check today. Thank you!

**Comment by danieldahan** [comment] 2017-11-08 17:10
I am downloading the iOS 9 simulator to confirm this issue and will push a fix right away :)

**Comment by OrkhanAlikhanov** [comment] 2017-11-08 17:15
@danieldahan In code you only check `#available(iOS 11, *)`. I guess, the issue is non-ios11-specific :)

**Comment by danieldahan** [comment] 2017-11-08 17:16
Yes, it was in iOS 10 as well. I missed this when I was updating everything for iOS 11. Thanks guys. The fix is in [Material 2.12.15](https://github.com/CosmicMind/Material/releases/tag/2.12.15) :)

**Closed by danieldahan** 2017-11-08 17:16 UTC
Labels: bug, high priority, in progress, material
