### ISSUE TITLE
Later versions (2.12.1 and above) - Navigation Bar/Items don't show in iOS 10 and below

### ISSUE THREAD

**Issue by st34m3dr1c3** [CosmicMind/Material#924] opened 2017-10-20 04:56 UTC
Compiling with 2.12.1 and above seems to make the Material custom Navigation Bar and its Items show as blank white space in any iOS below 11. 

Deploying on iOS 11 and above seems to fix the issue.

Any advice on fixing this? Probably something small I'm missing.

**Comment by st34m3dr1c3** [comment] 2017-10-20 17:15
Note that this applies to the Github manual install. I am not using cocoapods.

**Comment by danieldahan** [comment] 2017-10-21 18:06
I am downloading the iOS 10 simulator and will check to see what the issue is. I will update you shortly. Thank you!

**Comment by danieldahan** [comment] 2017-10-22 19:49
Hey! I tried this on iOS 10.3.1 and all seems to look good. 

<img width="573" alt="screen shot 2017-10-22 at 1 48 43 pm" src="https://user-images.githubusercontent.com/9982123/31865675-d086d8be-b72f-11e7-874b-da0f83f5376f.png">

Anything I am missing, or can you send over a sample project please ?

**Comment by st34m3dr1c3** [comment] 2017-10-22 19:57
Hi Daniel,

Thanks for testing! I seem to find issues running even with your sample
project (try the storyboard sample from your Samples repository for
Navigation Controller).

Granted, I was deploying on real iOS devices and not on a simulator. If I
sourced the project to Material 2.12 and above, the navigation bar would
simply disappear. Sourcing back to Material 2.10 (as used in the Pods file
for the sample project) seemed to fix the issue.

Do you happen to have an iOS device that you could test on? It seems very
reproducible there.

Thanks again!

**Comment by danieldahan** [comment] 2017-10-24 13:51
I will take a look today :)

**Comment by danieldahan** [comment] 2017-10-25 23:51
@st34m3dr1c3 I confirmed the issue. I am working on a solution. Thank you for sharing this :)

**Comment by st34m3dr1c3** [comment] 2017-10-25 23:58
Thanks!

Also, I might add that in 2.10 the navigation bar is slightly offset to the
right by default.

See screenshot for details.

Cheers!

**Comment by danieldahan** [comment] 2017-10-26 00:04
I fixed it :) I will push to the development branch and would you be able to confirm?

**Comment by st34m3dr1c3** [comment] 2017-10-26 00:21
Yes, but I wont have a chance to test it on an iOS10 device until next
week. I will do so then and get back to you.

Thanks again!

**Comment by danieldahan** [comment] 2017-10-26 13:41
There is an issue I found with iOS 11 and sizing not behaving correctly. I will be fixing that with this fix as well.

**Comment by danieldahan** [comment] 2017-10-29 23:00
You can find this fixed in [Material 2.12.12](https://github.com/CosmicMind/Material/releases/tag/2.12.12). Thank you!

**Closed by danieldahan** 2017-10-29 23:00 UTC
Labels: bug, high priority, in progress, investigate

**Comment by shemchavez** [comment] 2017-11-30 08:59
Hey guys i fix this by adding this block of code after setting the Navigation Title:

self.navigationController?.navigationBar.setNeedsLayout()
self.navigationController?.navigationBar.layoutIfNeeded()
self.navigationController?.navigationBar.setNeedsDisplay()
