### ISSUE TITLE
NavigationBarView wrong layout without leftControl assignment at iOS 8.

### ISSUE THREAD

**Issue by TheHmmka** [CosmicMind/Material#200] opened 2016-03-02 16:15 UTC
Hi! Found a bug with iOS 8 and NavigationBarView.

<img width="487" alt="screenshot 2016-03-02 19 03 59" src="https://cloud.githubusercontent.com/assets/468660/13466145/bfe21a9a-e0a9-11e5-8c0c-b1a9e5486059.png">

```
UILabel* titleLabel = [[UILabel alloc] init];
titleLabel.textColor = [UIColor whiteColor];
titleLabel.textAlignment = NSTextAlignmentLeft;
titleLabel.font = SAN_FRANCISCO_REGULAR_17;
	
UILabel* detailLabel = [[UILabel alloc] init];
detailLabel.textColor = [UIColor whiteColor];
detailLabel.textAlignment = NSTextAlignmentLeft;
detailLabel.font = SAN_FRANCISCO_REGULAR_12;

self.navigationBarView = [[NavigationBarView alloc] initWithTitleLabel: titleLabel detailLabel: detailLabel leftControls: nil rightControls: nil];
self.navigationBarView.backgroundColor = self.navigationBarViewBackgroundColor;
[self.view addSubview: self.navigationBarView];

self.navigationBarView.titleLabel.text = NSLocalizedString(@"Settings section title", nil);
	
NSString* prefix = NSLocalizedString(@"Version text", nil);
NSString* version = [[[NSBundle mainBundle] infoDictionary] objectForKey: @"CFBundleShortVersionString"];
NSString* build = [[NSBundle mainBundle] objectForInfoDictionaryKey: (NSString*)kCFBundleVersionKey];
self.navigationBarView.detailLabel.text = [NSString stringWithFormat: @"%@: %@ (%@)", prefix, version, build];
```

**Comment by danieldahan** [comment] 2016-03-02 16:23
Nice! I am actually making a fix now to the NavigationBarView. Doesn't seem to be detecting the layout changes correctly. What version of Material are you using?

**Comment by TheHmmka** [comment] 2016-03-02 18:15
The latest sources from git.
I use Material.framework from Objective-C sources, but this should not be the reason, I hope.

**Comment by danieldahan** [comment] 2016-03-02 18:16
No, it shouldn't be an issue. It was some internal business I am fixing now.

**Comment by TheHmmka** [comment] 2016-03-02 18:17
Thanks for quick response and save my time. :+1:

**Comment by danieldahan** [comment] 2016-03-03 03:09
Please try version [1.35.1](https://github.com/CosmicMind/Material/releases/tag/1.35.1). If the issue persists, reopen the issue or create a new one. Thank you for submitting this.

**Comment by TheHmmka** [comment] 2016-03-03 05:11
Sorry, but issue not fixed by 1.35.1 build.

**Comment by danieldahan** [comment] 2016-03-03 06:36
Yes, that was an accident, to say this issue was completed. For this issue, I have a fix that I will implement in the morning.

**Comment by TheHmmka** [comment] 2016-03-03 06:39
:+1:

**Comment by danieldahan** [comment] 2016-03-03 06:54
Are you using storyboards?

**Comment by TheHmmka** [comment] 2016-03-03 06:55
Nope. Manual control of navigations and transitions. Create this components in viewDidLoad.

**Comment by danieldahan** [comment] 2016-03-03 07:38
Originally, I thought this was an issue with storyboards. Now I see this line:

```swift
self.navigationBarView = [[NavigationBarView alloc] initWithTitleLabel: titleLabel detailLabel: detailLabel leftControls: nil rightControls: nil];
```

I notice that your font size for the `detailLabel` is large, and should be size 12. Nothing looks incorrect from your example code, except that line.

**Comment by danieldahan** [comment] 2016-03-03 07:39
Can you try setting the text for both titleLabel and detailLabel before constructing the NavigationBarView?

**Comment by TheHmmka** [comment] 2016-03-03 07:47
Yep, I tried but no success. This issue disappear only with set up left control.

```
UILabel* titleLabel = [[UILabel alloc] init];
titleLabel.textColor = [UIColor whiteColor];
titleLabel.textAlignment = NSTextAlignmentLeft;
titleLabel.font = SAN_FRANCISCO_REGULAR_17;
titleLabel.text = @"Hello";
	
UILabel* detailLabel = [[UILabel alloc] init];
detailLabel.textColor = [UIColor whiteColor];
detailLabel.textAlignment = NSTextAlignmentLeft;
detailLabel.font = SAN_FRANCISCO_REGULAR_12;
detailLabel.text = @"Hello";

self.navigationBarView = [[NavigationBarView alloc] initWithTitleLabel: titleLabel	detailLabel: detailLabel leftControls: nil rightControls: nil];
self.navigationBarView.backgroundColor = self.navigationBarViewBackgroundColor;
[self.view addSubview: self.navigationBarView];
```

**Comment by TheHmmka** [comment] 2016-03-03 07:48
Do you use Autolayouts? May be the problem with dependencies in it?

**Comment by danieldahan** [comment] 2016-03-03 07:52
No, the NavigationBarView is created without any AutoLayouts.

**Comment by danieldahan** [comment] 2016-03-03 07:54
Very strange, I cannot reproduce this. Can you try using the system font, and not San Fran?

**Comment by TheHmmka** [comment] 2016-03-03 07:56
I removed fonts from my code and no success.

**Comment by danieldahan** [comment] 2016-03-03 07:58
Okay, clearly there is something going on here. It is late now, so I will work on this tomorrow. I am currently using Swift, so tomorrow, I will check with an Objective-C approach.

**Comment by TheHmmka** [comment] 2016-03-03 07:58
No problems! Thanks!

**Comment by danieldahan** [comment] 2016-03-04 22:51
I made some updates that may resolve this in [1.35.3](https://github.com/CosmicMind/Material/releases/tag/1.35.3). I am not expecting it too. Over the weekend, I will be diving deeper into your issue and seeing what has happened. Thanks for your patience.

**Comment by TheHmmka** [comment] 2016-03-05 06:41
Yep! Everything is fine. Thank you!

**Comment by danieldahan** [comment] 2016-03-05 19:18
It is working now?

**Comment by TheHmmka** [comment] 2016-03-07 06:27
Yep! Thanks!

2016-03-05 22:18 GMT+03:00 Daniel Dahan <notifications@github.com>:

**Comment by danieldahan** [comment] 2016-03-07 06:28
Sweet! Then I am closing this issue. Thank you! :)

**Closed by danieldahan** 2016-03-07 06:28 UTC
Labels: help wanted
