### ISSUE TITLE
On secure text details label has weird behavior

### ISSUE THREAD

**Issue by juvs** [CosmicMind/Material#295] opened 2016-04-12 00:25 UTC
If you set secure for textfield (lets call "password"), and, lets said you validate emptiness and set detail label to some text after you press "go" on keyboard or "done" button, first time woks ok...

![screen shot 2016-04-11 at 7 20 27 p m](https://cloud.githubusercontent.com/assets/204912/14446374/f2e7b8a6-001a-11e6-84aa-9411adb23f2f.png)

But if you get focus of password again and press "go" on keyboard or "done" button again, and set detail label with the error again, only shows the red underline for the field and not the detail label text weird.

![screen shot 2016-04-11 at 7 19 52 p m](https://cloud.githubusercontent.com/assets/204912/14446377/f881b276-001a-11e6-9502-92c31a3c04d3.png)

Normally, when you call "go" or "done" the `resignFirstResponder` or `view.endEditing(true)` is call to dismiss the keyboard and in a regular textfield works ok! but password seems to call the hide and show details label almost at the same time, so when ends the animations, hide wins!.

**Comment by danieldahan** [comment] 2016-04-12 15:30
I am unable to verify this. Maybe you need to set this value?

```swift
textField.detailLabelAutoHideEnabled = false
```

Please confirm, or possibly give step by step instructions to reproduce. I know above you did outline steps, but all seems to work for me.

**Comment by danieldahan** [comment] 2016-04-13 19:18
So I am not able to reproduce this issue. If you can provide an example project or more guidance that would be great. Until then, I am going to close this issue. Please feel free to reopen or create a new one if the issue persists.

**Closed by danieldahan** 2016-04-13 19:18 UTC
Labels: help wanted

**Comment by juvs** [comment] 2016-04-13 21:18
Sorry for the delay... 
Using `textField.detailLabelAutoHideEnabled = false` and later when done the validation manually call `textField.detailLabelHidden = true` or `textField.detailLabelHidden = false` depending the result of validation.

I see this more like a workaround, because the normal behavior works ok for "normal" textfields. 
Thanks for you help

**Comment by danieldahan** [comment] 2016-04-13 22:04
If you can provide me a working example project, I would love to solve this without work arounds. I still consider Material to be at the foundation stage, and I want that to be as solid as possible :)
