### ISSUE TITLE
Programatically Set Text on TextField

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#338] opened 2016-04-25 08:45 UTC
Setting `textField.text` programatically has some weird side effects on the `titleLabel` after interaction.

**Comment by danieldahan** [comment] 2016-04-25 15:31
Can elaborate on what is the weird side effects?

**Comment by zgosalvez** [comment] 2016-04-25 15:33
The title label does not appear

**Comment by danieldahan** [comment] 2016-04-25 15:35
Are you setting a placeholder? I will try now.

**Comment by zgosalvez** [comment] 2016-04-25 15:38
Yes, a placeholder is also set.

**Comment by danieldahan** [comment] 2016-04-25 16:16
This is a confirmed bug. I will fix it today.

**Comment by saipnc** [comment] 2016-04-26 07:42
@danieldahan yes we are also facing the same issue if we set text programmatically the title label disappears with a weird animation. If you could fix this it would be great.

**Comment by saipnc** [comment] 2016-04-26 08:56
Hey, @danieldahan 

After going through your code, I figured out that by setting the test field data programmatically the delegate methods are not getting invoked. Because of which the title label is not getting set. 

Ex: When we type in text field the delegates are called and the title label is set, but when we set text like textField.text = "Something" then delegates are not called and title label is not set

**Comment by zgosalvez** [comment] 2016-04-26 09:09
I tried doing the following "hack," but didn't work, probably because of race conditions with the animations.

```swift
textField.sendActionsForControlEvents(.EditingDidBegin)
textField.text = "something"
textField.sendActionsForControlEvents(.ValueChanged)
textField.sendActionsForControlEvents(.EditingDidEnd)
```

**Comment by danieldahan** [comment] 2016-04-26 15:10
Yeah that would cause an issue. I am working on documentation for this release today with a fix.

**Comment by saipnc** [comment] 2016-04-28 06:50
Hi @danieldahan,

We need this bug fixed very badly, how long does this take?

**Comment by danieldahan** [comment] 2016-04-28 12:10
@mohpor @saipnc @zgosalvez Hi, I rewrote the TextField, under the temporary class [MTextField](https://github.com/CosmicMind/Material/blob/development/Sources/iOS/MTextField.swift) and added an example of its usage in the Programmatic/TextField example project. My aim is to simplify the interface and have a cleaner code base going forward. @zgosalvez I have spent quite a bit of time making sure that it follows the spec as best as iOS can. There is some a little more work to do, not much and then I can release it. I was hoping you guys would be able to take a look. I have also been working on a documentation site, which I will push later today. 

Things to note: 

* I have removed the default clearButton - found that conflicted with the iOS clearButton. 
* I have simplified the API and want to keep it as minimal as possible. 
* I have rethought the entire approach of dealing with TextFields and input animations. 
* I need to added placeholder highlighting, formally known as title -> this should be an easy step. 

Thanks guys, I will be finalizing this today, and then moving to AlertView, pulse animation, and SideNav.

**Comment by danieldahan** [comment] 2016-04-28 14:43
@saipnc @zgosalvez please take part in this [issue](https://github.com/CosmicMind/Material/issues/342).

**Comment by danieldahan** [comment] 2016-04-30 23:20
@saipnc You can now do this in the new TextField, temporary name MTextField, which is now in development. Please track any changes prior to release here [342](https://github.com/CosmicMind/Material/issues/342). I am closing this issue to consolidate all TextField issues in 342.

**Closed by danieldahan** 2016-04-30 23:20 UTC
Labels: bug, help wanted, question

**Comment by saipnc** [comment] 2016-05-02 06:34
@danieldahan Thank you so much!
