### ISSUE TITLE
TabsController transition sets alpha of views to 1.0

### ISSUE THREAD

**Issue by andrewc94** [CosmicMind/Material#1022] opened 2018-01-14 23:30 UTC
I'm using a control which has a set of invisible labels and set of visible labels. During my first transition to a view controller which contains this control, all the labels are visible when half should be invisible. I'm not sure what's causing this but using a UITabBarController does not have this problem.

- I'm using XCode 9.2, Material 2.13.4, Motion 1.3.3.
- Subsequent transitions don't set alphas to 1.0, just the first one
- possible related issues: https://github.com/CosmicMind/Material/issues/853, https://github.com/CosmicMind/Motion/issues/16
- What I'm seeing:
<img width="727" alt="screen shot 2018-01-14 at 2 55 24 pm" src="https://user-images.githubusercontent.com/8138866/34922048-582795fa-f93f-11e7-99c6-5b341507aef7.png">
- What it should look like:
<img width="745" alt="screen shot 2018-01-14 at 3 27 33 pm" src="https://user-images.githubusercontent.com/8138866/34922058-856357c0-f93f-11e7-8bf1-ca4027060f57.png">

**Comment by danieldahan** [comment] 2018-01-15 18:42
Thank you for sharing this issue. I am going to investigate it tonight. In the meantime, if you have a sample project that reproduces the issue, that would be great.

**Comment by andrewc94** [comment] 2018-01-15 22:39
Here you go, switch between the tabs to see the issue.
[Test.zip](https://github.com/CosmicMind/Material/files/1633144/Test.zip)

**Comment by danieldahan** [comment] 2018-01-15 22:43
Thank  you! @andrewc94

**Comment by andrewc94** [comment] 2018-01-15 22:57
Also not sure if this is helpful, but here's the stack trace where the label's alpha is set to 1 from 0 during the transition.

<img width="457" alt="screen shot 2018-01-15 at 2 54 53 pm" src="https://user-images.githubusercontent.com/8138866/34964819-49eb2d6a-fa04-11e7-8c84-19559e38a0b3.png">

**Comment by danieldahan** [comment] 2018-01-17 17:50
Hey sorry for any delays with this issue. @adamdahan let's both take a look at this one.

**Comment by adamdahan** [comment] 2018-01-17 18:03
@andrewc94 Stacktrace very useful thank you. Will look more into this tonight :)

**Comment by adamdahan** [comment] 2018-01-18 05:46
@andrewc94 Thank you for the test project and stacktrace 👍 

I have confirmed the issue in the latest version of Material and found the root cause of the issue with your help. I will confirm a fix with @danieldahan and make sure this is addressed in the next release.

Will keep this ticket open until it's fully resolved. 😄

**Comment by andrewc94** [comment] 2018-01-18 05:56
@adamdahan 
Thank you so much!! Would it be possible to give a high level explanation of what was going on?

**Comment by danieldahan** [comment] 2018-01-19 19:49
@adamdahan I fixed the alpha issue. We will make a push tonight.

**Comment by danieldahan** [comment] 2018-01-19 19:52
@andrewc94 Thank you for sharing this issue, thank you @adamdahan for discovering the solution. The fix is in development and will be pushed later today.

**Closed by danieldahan** 2018-01-19 19:52 UTC
Labels: help wanted, high priority, in progress, investigate, material
