### ISSUE TITLE
FAB button image not showing after init

### ISSUE THREAD

**Issue by tomdaniel0x01** [CosmicMind/Material#907] opened 2017-10-14 01:01 UTC
I have created a FAB button using `fabButton = FABButton(image: Icon.cm.add, tintColor: Color.grey.darken3)` but the image does not display until the button is touched.

I have tried setting the image outside of init which still does not work.

**Comment by danieldahan** [comment] 2017-10-14 02:18
Would you be able to send me a sample showing this? Is this tested on the simulator or device? What version of Material are you using? Thank you!

**Comment by danieldahan** [comment] 2017-10-15 21:07
Hey! I haven't heard from you. When you have a sample project reproducing the issue, please reopen this. Thank you!

**Comment by tomdaniel0x01** [comment] 2017-10-16 18:05
Here is an xcode project that I created that reproduces this issue: https://github.com/tomdaniel0x01/fab-menu-bug

I am using Material (2.12.1) and it happens on both the simulator and the device.

**Comment by danieldahan** [comment] 2017-10-16 21:42
Thank you! I will take a look :)

**Comment by danieldahan** [comment] 2017-10-19 16:09
@tomdaniel0x01 So I found the bug. The issue arises because the size is being set after the left and bottom positioning. I am looking into it. You can workaround this issue by moving the size constraint before the position constraints: 

```swift
view.layout(fabMenu).size(CGSize(width: 56, height: 56)).bottom(17).left(10)
```

**Comment by danieldahan** [comment] 2017-10-19 17:08
The issue has been completely resolved in [Material 2.12.3](https://github.com/CosmicMind/Material/releases/tag/2.12.3). Thank you for sharing this issue. All the best!

**Closed by danieldahan** 2017-10-19 17:08 UTC
Labels: help wanted, investigate, waiting on Daniel

**Comment by tomdaniel0x01** [comment] 2017-10-19 18:33
@danieldahan Thank you so much!

**Comment by yasirmturk** [comment] 2017-10-25 07:57
this fix broke something inside the button and now `titleEdgeInsets` and `imageEdgeInsets` are not working properly for `Button`, `IconButton`

**Comment by danieldahan** [comment] 2017-10-25 12:44
@yasirmturk Can you share a sample or some code that demonstrates this and your usage?

**Comment by yasirmturk** [comment] 2017-10-25 16:05
I am aligning icon and text in horizontal centered position and for that is used this code
`extension Button {
    // MARK: - UIButton+Aligment
    
    func alignContentHorizontally(spacing: CGFloat = 4.0) {
        contentHorizontalAlignment = .left
        contentVerticalAlignment = .top
        
        let imageWidth = (currentImage?.width)!
        let imageLeft = (layer.width - imageWidth) / 2
        let titleLeft = ((layer.width - (titleLabel?.layer.width)!) / 2) - imageWidth
        imageEdgeInsets = UIEdgeInsetsMake(spacing, imageLeft, 0, 0)
        titleEdgeInsets = UIEdgeInsetsMake(24 + (spacing * 2), titleLeft, 0, 0)
    }
}`
to get this: 
![iconbuttons-tabbar-2_12_2](https://user-images.githubusercontent.com/306691/32009198-cf0b7824-b9c7-11e7-855e-209c0e4a2f6a.jpg)
It was working perfect till version 2.12.2 but after updating to version 2.12.3 it became this: 
![2 12 3](https://user-images.githubusercontent.com/306691/32009303-2c8d8e42-b9c8-11e7-855c-966837267886.png)

**Comment by danieldahan** [comment] 2017-10-25 16:09
@yasirmturk Can you send over a sample of this, so I can reproduce the issue? As well, I would open a new issue for this, as now the this issue has been closed and the description at the top is not describing the issue you are facing. Thank you!

**Comment by yasirmturk** [comment] 2017-10-26 07:58
you can use the code i have posted to reproduce the issue... just make any button with both icon and text and run it with both 2.12.2 and 2.12.3 you will see

**Comment by danieldahan** [comment] 2017-10-26 13:45
@yasirmturk Please open a new issue for this. Tagging this issue on the current one is not effective. Thank you :)

**Comment by yasirmturk** [comment] 2017-10-26 15:05
okay
