### ISSUE TITLE
App Example project

### ISSUE THREAD

**Issue by levuhai** [CosmicMind/Material#311] opened 2016-04-15 04:02 UTC
In your App example Delegate.swift

When setting SideNavigationController rootViewController as AppMenuViewController, when opening side menu, the whole view won't slide up

let sideNavigationController: SideNavigationController = SideNavigationController(rootViewController: menuViewController, leftViewController: AppLeftViewController())

While setting its root view controller as AppNavigationController, the whole view slide up when opening side menu
let sideNavigationController: SideNavigationController = SideNavigationController(rootViewController: navigationController, leftViewController: AppLeftViewController())

I don't want the whole view to slide up when using navigation controller inside side navigtaion controller.
Do you have any idea i can change this?

Thank you so much for your hard work

**Comment by danieldahan** [comment] 2016-04-15 14:39
This is a weird issue with Apples approach to hiding the statusBar. I have been playing with ways to make it work, and so far the only way is the using the menuViewController as you stated above. I will leave this issue up and see if I can come up with a better approach.

**Comment by danieldahan** [comment] 2016-05-01 23:44
@levuhai In the example project, I eliminate this issue, by using a view hierarchy that you can see in the AppDelegate, App example project in the programmatic directory. The issue is, Apple detects the NavigationController at the point of contact to the edge of the screen, if that makes any sense, and then they decide to animate the statusBar to a hidden state. I will continue to see if I can make it easier to work with, rather than the hierarchy setting that has been the only successful and non cumbersome approach. I plan to rewrite the NavigationController within the month of May. I am going to close this for now, as I have noted the issue and agree it should be resolved within the rewrite. Although, this is really how Apple handles the situation, so technically, it is not an error or bug.

**Closed by danieldahan** 2016-05-01 23:44 UTC
Labels: help wanted
