### ISSUE TITLE
NavigationDrawerController and menu button

### ISSUE THREAD

**Issue by ayham-achami** [CosmicMind/Material#977] opened 2017-11-20 13:13 UTC
if press on menu button on navigation bar and move finger to left, the left view controller will close, but the content view stay on screen, and block the user interactions. 

![nov-20-2017 15-54-39](https://user-images.githubusercontent.com/28861684/33019511-bcaf9108-ce0b-11e7-8aaf-c38ef112c91a.gif)

**Comment by danieldahan** [comment] 2017-11-20 13:27
Hey! I tried the sample project now, [NavigationDrawerController sample](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController), and all seems to work. Can you confirm on the latest and on the sample this issue exists? If not, we will need to investigate your setup. Thank you!

**Comment by ayham-achami** [comment] 2017-11-20 14:34
i'm use the last version of Material (2.12.16) and the issue exits for left and right view controller.

**Comment by danieldahan** [comment] 2017-11-20 14:34
Have you tried it with the sample, because I did and there is not an issue.

**Comment by ayham-achami** [comment] 2017-11-20 14:43
yes i tried it with the sample, and this a gif from your sample.

![nov-20-2017 17-38-10](https://user-images.githubusercontent.com/28861684/33023601-be96a9bc-ce19-11e7-9908-4535a0bf8f93.gif)

**Comment by danieldahan** [comment] 2017-11-20 14:45
This is not happening to me with the latest and same simulator. Can you ensure that you are not loading cached copy or something corrupt, because I cannot reproduce this issue?

**Comment by ayham-achami** [comment] 2017-11-20 14:50
you swipe to left when tap on left UIBarButtonItem ?

**Comment by danieldahan** [comment] 2017-11-20 14:54
Here is what I get: 

![nabdrawer](https://user-images.githubusercontent.com/9982123/33024313-5deacc18-cdd0-11e7-8a83-f13b885efe0d.gif)

**Comment by danieldahan** [comment] 2017-11-20 15:50
I am closing this issue for now. If you send me a reproducible project, I will reopen this. Thank you!

**Comment by ayham-achami** [comment] 2017-11-21 08:27
i think you don't understand how to bring this bug, please, use the gesture on the menu button EXACTLY as I was showing. As if you want to throw the button off the screen.

**Comment by danieldahan** [comment] 2017-11-21 16:22
Ah I see, well two things. One you are using a normal UINavigationController, the sample used a Material NavigationController. Second, you are doing this on a simulator, which means you might be breaking the touch events when the cursor goes off the simulator screen area. I would check this on a real device and send me a reproducible project. If you need any further help, let me know :)

**Comment by ayham-achami** [comment] 2017-11-23 09:32
this issue is exists for real devices, and i replaced a normal UINavigationController with Material NavigationController the issue still exists for simulator and real device, and this is a reproducible [project.](https://github.com/ayham-achami/SampleNavigationDrawerController.git)

please make look for two methods in NavigationDrawerController `handleLeftViewPanGesture(recognizer:)  handleRightViewPanGesture(recognizer:)`

the methods `closeLeftView(velocity:)` and `closeRightView(velocity:)` has called before the side view controller has opened.

**Comment by danieldahan** [comment] 2017-11-23 12:52
Thank you, I will take a look :)

**Comment by danieldahan** [comment] 2017-11-23 16:24
I see now what you are saying. I can reproduce the issue. I'll take a look :)

**Comment by ToonvanStrijp** [comment] 2017-11-23 18:08
I had the same issue, you must add a UITapGestureRecognizer like this: `menuButton.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(handleMenuButton)))`

**Comment by danieldahan** [comment] 2017-11-23 18:58
@ToonvanStrijp I will add fix that removes the need to add the UITapGestureRecognizer.

**Comment by muzoman** [comment] 2017-12-01 13:38
Hi @danieldahan, have you had time to look at this yet? I see this behaviour in my App too.

**Comment by Spr-Luis** [comment] 2017-12-02 02:16
I have same issue, is a problem in iOS 10, because the toolbar is before the button.

**iOS 10**

<img width="746" alt="captura de pantalla 2017-12-01 a la s 20 15 55" src="https://user-images.githubusercontent.com/5206221/33510674-7a401906-d6d4-11e7-93ec-822b3f26a6ac.png">

**iOS 11**

<img width="703" alt="captura de pantalla 2017-12-01 a la s 20 13 35" src="https://user-images.githubusercontent.com/5206221/33510649-2529f860-d6d4-11e7-8827-6b62698ba4da.png">

**Material 2.12.17**

**Comment by danieldahan** [comment] 2017-12-04 14:53
Hey, sorry for the delay. I was on vacation. I will take a look today :)

**Comment by aemgtz** [comment] 2017-12-06 12:10
I can confirm that is a bug.

**Step to reproduce**
-  Press on the menu and swipe backward then the screen is stuck with dim background.

Material : 2.9.4

**Comment by danieldahan** [comment] 2017-12-06 14:36
@aemgtz Thank you. I am investigating the issue.

**Comment by aemgtz** [comment] 2017-12-07 06:36
Here is my work around solution. 
You have to subclass the NavigationDrawerController and override the receive touch delegate then add the condition to cancel  touch event for specific view type.

`
import UIKit
import Material

class AppNavigationDrawer: NavigationDrawerController {

    override func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        if (touch.view?.isKind(of: IconButton.classForCoder()))!{
            print("Cancel touch when view is IconButton")
            return false
        }
        return super.gestureRecognizer(gestureRecognizer, shouldReceive: touch)
    }
}

`

**Comment by danieldahan** [comment] 2017-12-07 14:38
Can you try this commit and tell me if the issue has been fixed, 9d03ba4ebfebc1debe0f901098a9cbd3e881c453. Thank you!

**Comment by aemgtz** [comment] 2017-12-07 15:23
I tried with Material 2.12.19. 
This issue doesn't occur anymore. 
Thank you!

**Comment by ayham-achami** [comment] 2017-12-07 18:04
@danieldahan Thank you! it's work for me too.
tell me please when you will make a release with this fix?

**Comment by danieldahan** [comment] 2017-12-07 18:15
@ayham-achami nice, I will make a release now :)

**Closed by danieldahan** 2017-12-07 18:15 UTC
Labels: good first issue, help wanted, high priority, in progress, investigate, material, waiting for response

**Comment by danieldahan** [comment] 2017-12-07 18:22
Released in [Material 2.12.19](https://github.com/CosmicMind/Material/releases/tag/2.12.19). Thank you!
