### ISSUE TITLE
Toolbar right items are not shown

### ISSUE THREAD

**Issue by leobouilloux** [CosmicMind/Material#436] opened 2016-06-10 15:11 UTC
Hi!

I have a problem using your toolbar component.
It occurred since I've update your framework to version 1.41.8 (the last update atm).
For the moment, I went back to 1.41.6 and my right control is displayed correctly.

Maybe I'm not using it correctly.
Just in case, here is my code:
```swift
    private func prepareToolbar() {
        toolbar = Toolbar()
        shareView.addSubview(toolbar)
        
        // Title label.
        toolbar.titleLabel.text = "Share \(node.loadName()!)"
        toolbar.titleLabel.textColor = MaterialColor.white
        
        var image: UIImage? = MaterialIcon.cm.share
        
        // Menu button.
        let mailButton: IconButton = IconButton()
        mailButton.pulseColor = MaterialColor.white
        mailButton.tintColor = MaterialColor.white
        mailButton.setImage(image, forState: .Normal)
        mailButton.setImage(image, forState: .Highlighted)
        
        // Search button.
        image = MaterialIcon.cm.close
        let closeButton: IconButton = IconButton()
        closeButton.pulseColor = MaterialColor.white
        closeButton.tintColor = MaterialColor.white
        closeButton.setImage(image, forState: .Normal)
        closeButton.setImage(image, forState: .Highlighted)
        closeButton.addTarget(self, action: #selector(ShareViewControllerMaterial.closeButtonPressed), forControlEvents: .TouchUpInside)
        
        toolbar.backgroundColor = MaterialColor.blue.base
        toolbar.leftControls = [mailButton]
        toolbar.rightControls = [closeButton]
    }
```

**Comment by danieldahan** [comment] 2016-06-10 15:14
Hi :) 

What is shareView?

**Comment by leobouilloux** [comment] 2016-06-10 15:18
Here it is:
``` swift
    private func prepareShareView() {
        shareView = MaterialView()
        shareView.backgroundColor = MaterialColor.white
        shareView.depth = MaterialDepth.Depth5
        shareView.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(shareView)

        let top: CGFloat = 20 + 44 + 76
        MaterialLayout.alignToParent(view, child: shareView, top: top, left: 0, bottom: 0, right: 0, options: .AlignAllBaseline)
    }
```
view is the default UIViewController view

**Comment by chashmeetsingh** [comment] 2016-06-10 15:21
the problem is I suppose you should add subview at the end ?

**Comment by danieldahan** [comment] 2016-06-10 15:22
If he doesn't add SubView prior to using MaterialLayout, it will crash, because the view is not added to the hierarchy when trying to calculate the layouts.

**Comment by mohpor** [comment] 2016-06-10 15:23
@leobouilloux Hi :)
 could you elaborate more on the issue you're having?

**Comment by chashmeetsingh** [comment] 2016-06-10 15:25
@danieldahan I meant in prepareToolbar()

**Comment by danieldahan** [comment] 2016-06-10 15:36
@chashmeetsingh good point.

**Comment by leobouilloux** [comment] 2016-06-10 15:42
BTW I noticed that a problem occurs with the example in the sample solution:
Sample project Toolbar code:
```swift
	private func prepareToolbar() {
		toolbar = Toolbar()
		containerView.addSubview(toolbar)
		
		// Title label.
		toolbar.title = "Material"
		toolbar.titleLabel.textColor = MaterialColor.white
		
		// Detail label.
		toolbar.detail = "Build Beautiful Software"
		toolbar.detailLabel.textColor = MaterialColor.white

		var image: UIImage? = MaterialIcon.cm.menu

		// Menu button.
		let menuButton: IconButton = IconButton()
		menuButton.pulseColor = MaterialColor.white
		menuButton.tintColor = MaterialColor.white
		menuButton.setImage(image, forState: .Normal)
		menuButton.setImage(image, forState: .Highlighted)

		// Switch control.
		let switchControl: MaterialSwitch = MaterialSwitch(state: .Off, style: .LightContent, size: .Small)

		// Search button.
		image = MaterialIcon.cm.search
		let searchButton: IconButton = IconButton()
		searchButton.pulseColor = MaterialColor.white
		searchButton.tintColor = MaterialColor.white
		searchButton.setImage(image, forState: .Normal)
		searchButton.setImage(image, forState: .Highlighted)
		
		/*
		To lighten the status bar - add the
		"View controller-based status bar appearance = NO"
		to your info.plist file and set the following property.
		*/
		toolbar.backgroundColor = MaterialColor.blue.base
		toolbar.leftControls = [menuButton]
		toolbar.rightControls = [switchControl, searchButton]
	}
```
![simulator screen shot 10 jun 2016 17 24 59](https://cloud.githubusercontent.com/assets/1726316/15969572/f4b2b6aa-2f30-11e6-9fd2-f2de0bf6db88.png)
![simulator screen shot 10 jun 2016 17 25 17](https://cloud.githubusercontent.com/assets/1726316/15969576/f8d09ef0-2f30-11e6-808f-83675c24a5be.png)

@mohpor Hi :)
My problem is that the close button is not displayed on my toolbar on the right (see screenshot below)
![simulator screen shot 10 jun 2016 17 37 02](https://cloud.githubusercontent.com/assets/1726316/15969944/7c497dbe-2f32-11e6-81e3-307502c65543.png)

Hope it helps and thank you so much for your help.

**Comment by danieldahan** [comment] 2016-06-10 15:43
I s this with the latest changes? 1.41.8

**Comment by leobouilloux** [comment] 2016-06-10 15:45
The close button was no longer displayed when I updated to 1.41.8.
The last screenshot is version 1.41.6

**Comment by chashmeetsingh** [comment] 2016-06-10 15:46
@danieldahan he's right the example toolbar right alignment is not getting applied (checked in the example)

**Comment by danieldahan** [comment] 2016-06-10 15:56
There is a verified bug here. It shall be fixed. Thank you!

**Comment by chashmeetsingh** [comment] 2016-06-10 15:58
same with dev branch (view.layout) update causing an error

**Comment by danieldahan** [comment] 2016-06-10 15:59
@chashmeetsingh that's because the call is incomplete. It needed to be updated.

**Comment by chashmeetsingh** [comment] 2016-06-10 15:59
ok! thanks :)

**Comment by mohpor** [comment] 2016-06-10 15:59
This is simply solvable by setting a Frame for your toolbar.

for example:
`toolbar = Toolbar(frame: CGRect(x: 0, y: 0, width: shareView.bounds.width, height: 32.0))`

**Comment by danieldahan** [comment] 2016-06-10 16:01
Yes, but there is a regression here and it should be fixed. 

also @chashmeetsingh this is the updated line 

```swift
view.layout.align.edges(containerView, top: 100, left: 20, right: 20)
```

**Comment by chashmeetsingh** [comment] 2016-06-10 16:02
thanks for the info @danieldahan 👍

**Comment by leobouilloux** [comment] 2016-06-10 16:09
Thank you very much for your help, I'll use your suggestions 👍

**Comment by danieldahan** [comment] 2016-06-10 16:42
This has been solved and will be fixed in the next release. I will leave the issue up until that release. Once again, thanks for bringing it to our attention.

**Comment by danieldahan** [comment] 2016-06-14 04:08
Hi, sorry for the delay, please try [1.42.0](https://github.com/CosmicMind/Material/releases/tag/1.42.0) for a fix. If the issue persists, please reopen or create a new issue. Thank you!

**Closed by danieldahan** 2016-06-14 04:08 UTC
Labels: Regression
