### ISSUE TITLE
Navigation Left & Right Views position

### ISSUE THREAD

**Issue by shemchavez** [CosmicMind/Material#995] opened 2017-12-11 06:50 UTC
Why they have great amount of space?

Image attached below.

![screen shot 2017-12-11 at 2 48 38 pm](https://user-images.githubusercontent.com/19364885/33818918-945aa288-de82-11e7-9dc8-bea781d679eb.png)

**Comment by danieldahan** [comment] 2017-12-20 20:13
This is an iOS 11 issue. iOS 11 adds some spacing. This issue has been noted internally and will be potentially fixed in Material 3, if a work around has not been added before hand. I will leave this up as a reminder. Thank you!

**Comment by intoxicated** [comment] 2018-02-09 05:56
@danieldahan would you mind if I can fix this with work around and PR? it seems like its related to UIStackView with iOS 11 that they added up some constraint it internally.

**Comment by danieldahan** [comment] 2018-02-12 17:18
@intoxicated I would appreciate your help very much. Let me know what I can do to help you fix this. Thank you!

**Comment by intoxicated** [comment] 2018-02-12 21:17
@danieldahan i'll set up project and play around with it for a couple day :) ill let you know

**Comment by danieldahan** [comment] 2018-02-12 22:26
@intoxicated excellent, thank you! From Friday to Tuesday I will not be around, so please, if you need me, ping me before or after that time.

**Comment by intoxicated** [comment] 2018-02-25 09:33
@danieldahan sorry I was quite busy last couple weeks! Now I'm investigating NavigationBar, NavigationItem part. 

1. Am I on right track? 
2. It seems like indentation for code base somewhat mixup with 4 and 2. And as far as I know, indentation 2 is preferable for swift. 
3. Material.Toolbar seems like having inset (left/right).
<img width="1020" alt="screen shot 2018-02-25 at 6 30 20 pm" src="https://user-images.githubusercontent.com/848531/36639956-4ae8a80c-1a5a-11e8-97f2-24b3e7e82f50.png">

**Comment by intoxicated** [comment] 2018-02-25 10:00
Further investigation, I found Material.Toolbar was being layout with Grid class, which showed below properties. 
<img width="490" alt="screen shot 2018-02-25 at 6 56 51 pm" src="https://user-images.githubusercontent.com/848531/36640219-db104676-1a5d-11e8-96db-59aa35f23db5.png">

So I suspect that Grid (layout system that Material use) somewhat set contentView (Material.Toolbar) to start at x: 49. Let me know what you think

**Comment by intoxicated** [comment] 2018-02-25 10:54
Fixed on #1038 and I confirmed with running sample NavigationController. Any feedbacks would be appreciated!

**Comment by OrkhanAlikhanov** [comment] 2018-06-02 18:58
@danieldahan Can we close this? Because #1038 is merged and is said to solve this issue.

It would be better to get feedback from @shemchavez though.

**Comment by shemchavez** [comment] 2018-06-03 02:27
Hey, would check this tomorrow. Thanks by the way for fixing it.

**Comment by danieldahan** [comment] 2018-06-06 20:57
Yes this is fine to close. Thank you!

**Closed by danieldahan** 2018-06-06 20:57 UTC
Labels: good first issue, material, question, waiting on support
