### ISSUE TITLE
TabsController indicator line bug

### ISSUE THREAD

**Issue by melcug** [CosmicMind/Material#824] opened 2017-08-04 11:26 UTC
I use following code to initialize TabBar:
```
extension AppTabBarController {
    fileprivate func prepareTabBar() {
        tabBarAlignment = .top
        tabBar.tabBarStyle = .auto
        tabBar.dividerColor = nil
        tabBar.lineHeight = 5.0
        tabBar.lineColor = Color.blue.lighten3
        tabBar.lineAlignment = .bottom
        tabBar.backgroundColor = Color.blue.darken2
    }
}
```
![2017-08-04 14 16 04](https://user-images.githubusercontent.com/8708178/28966818-e2dc5f40-7920-11e7-80c4-ec4f736badc5.gif)

As you can see, there are some problems with indicator line shown on active tab:
- initially the line is moving from top (not from bottom) of latest active tab to next active tab;
- the line height is ok at start, but changing the active tab to other tab it changes also the height of the line.

Regards,
Gogu.

**Comment by danieldahan** [comment] 2017-08-04 12:50
Nice, I will investigate this today :) Thank you!

**Comment by danieldahan** [comment] 2017-08-07 23:28
Thank you for submitting this issue. It is now fixed. I will push an update now.

**Closed by danieldahan** 2017-08-07 23:28 UTC
Labels: bug, investigate

**Comment by melcug** [comment] 2017-08-10 10:13
In latest version of Material (v2.9.1) following bug come back (fixed in v2.9.0):
- initially the line is moving from top (not from bottom) of first active tab to next active tab.

Regards,
Gogu.

**Comment by egenvall** [comment] 2017-08-23 17:41
This issue exists in v2.9.4 as well on the first swap between tabs

**Comment by danieldahan** [comment] 2017-08-23 17:42
I will double check.

**Comment by danieldahan** [comment] 2017-08-23 17:46
I cannot reproduce it. Are you sure you are using the latest? That said, if you can provide reproduction steps, that would be helpful. Thank you!

**Comment by egenvall** [comment] 2017-08-23 17:59
Using Material (2.9.4)

    class AppTabBarController: TabsController {
    
        override func viewDidLoad() {
            viewControllers = [someVc, someVc2]
            super.viewDidLoad()
        }
    

        open override func prepare() {
            super.prepare()
            tabBar.tabBarStyle = .auto
            tabBarAlignment = .top
            tabBar.dividerColor = nil
            tabBar.lineHeight = 5.0
            tabBar.lineColor = .red
            tabBar.lineAlignment = .bottom
            tabBar.backgroundColor = .white
        }
    }

The only difference I guess is that AppTabBarController is one of the tabs in [RamAnimatedTabBarController](https://github.com/Ramotion/animated-tab-bar) and then the  Material TabsController has two viewcontrollers that is set in the viewDidLoad

**Comment by danieldahan** [comment] 2017-08-23 18:01
Hmmm... well I cannot reproduce this within Material, you would have to setup a sample project with another library and demonstrate how Material breaks. Then I would be happy to help out.

**Comment by egenvall** [comment] 2017-08-23 18:30
It seems to be a storyboard issue.
    class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        window = UIWindow(frame: Screen.bounds)
        window!.rootViewController = AppTabsController(viewControllers: [])
        window!.makeKeyAndVisible()
    }
}


    class AppTabsController: TabsController {
    
    override func viewDidLoad() {
        viewControllers = [UIStoryboard(name: "Test", bundle: nil).instantiateViewController(withIdentifier: "blue"),UIStoryboard(name: "Test", bundle: nil).instantiateViewController(withIdentifier: "brown")]
        
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.navigationBar.isHidden = true
    }

    open override func prepare() {
        super.prepare()
        tabBar.tabBarStyle = .auto
        tabBarAlignment = .top
        tabBar.dividerColor = nil
        tabBar.lineHeight = 5.0
        tabBar.lineColor = .red
        tabBar.lineAlignment = .bottom
        tabBar.backgroundColor = .white
        tabBar.scrollView.showsVerticalScrollIndicator = false
        tabBar.scrollView.showsHorizontalScrollIndicator = false
        

        }
    }

Created a storyboard "Test" with 3 ViewControllers
- AppTabsController: Custom class AppTabsController
- BlueViewController: Custom class BlueViewController
- BrownViewController: Custom class BrownViewController


i.e it's not related to the other library

**Comment by danieldahan** [comment] 2017-08-23 18:59
I need a sample project that creates this issue. As well, you shouldn't need to set this: 

```
tabBar.scrollView.showsVerticalScrollIndicator = false
tabBar.scrollView.showsHorizontalScrollIndicator = false
```

They should already be set.

**Comment by egenvall** [comment] 2017-08-23 19:07
[Demo Repo](https://github.com/egenvall/TabsControllerBugRepo)
(Didn't clean away the other files from the sample)
Yes you are correct regarding the scrollview indicators.

**Comment by James-Coleman** [comment] 2018-11-16 11:12
@egenvall I know this is a really old issue and you may have already solved this, but I had this same issue and it was solved by setting up my tabBar appearance before calling super.viewDidLoad in my subclass of TabsController:

```
    override func viewDidLoad() {

        setupTabBarAppearance() // Setting up the tab bar appearance before super.viewDidLoad is removing the bug where the tab line would jump from the top to the bottom the first time a new tab is selected.
        
        super.viewDidLoad()
    }
```

I suspect this may be related to setting the `tabBarAlignment` to `.top`
