### ISSUE TITLE
FabButton doesnt goes in animation with delay

### ISSUE THREAD

**Issue by kruyvanna** [CosmicMind/Material#140] opened 2016-02-02 12:24 UTC
UIView.animateWithDuration(0.4, delay: 2, usingSpringWithDamping: 0.6, initialSpringVelocity: 0,      options: UIViewAnimationOptions.AllowUserInteraction, animations: {
                    self.aFabButton.frame.origin.x =400
         }, completion: nil)

The delayed is not applied at all.

When changing to use UIButton, the delay is applied

**Comment by danieldahan** [comment] 2016-02-02 15:40
Hi @kruyvanna, I know what the issue is. I am going to offer you a fix and then update Material to handle this issue. 

Some insight: All CALayers are by default animated, when altering properties etc. A UIView has a backing layer, that is a CALayer. When used through a UIView, the animations are disabled and only turned on when you use the UIView.animate.... block methods. In Material, we turn the animations on by default. So internally, there is a conflict that we need to handle. 

Here is a quick fix to give you the desired outcome, and in the next release, we will handle this issue and you will be able to use the UIView, without any additions. 

Fix: 

```swift
MaterialAnimation.delay(2) {
UIView.animateWithDuration(0.4, delay: 0, usingSpringWithDamping: 0.6, initialSpringVelocity: 0,      options: UIViewAnimationOptions.AllowUserInteraction, animations: {
                self.aFabButton.frame.origin.x =400
     }, completion: nil)
}
```

The next release will happen later today, but for now, this should work. Please reply to this issue to confirm it works, or later today when I make the release, I will close this issue.

**Comment by danieldahan** [comment] 2016-02-02 16:07
This is now fixed and will be in release 1.29.2

**Closed by danieldahan** 2016-02-02 16:07 UTC
Labels: help wanted

**Comment by kruyvanna** [comment] 2016-02-04 04:00
hi @danieldahan i confirm it's working.
Thanks for the insights!

**Comment by danieldahan** [comment] 2016-02-04 08:01
Excellent :) 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
