### ISSUE TITLE
ToolbarController release in SideNavigationController crash

### ISSUE THREAD

**Issue by bonroyage** [CosmicMind/Material#374] opened 2016-05-13 07:20 UTC
Hi,

I have setup a SideNavigationController with three menu items. Two of the items load a ToolbarController and load fine. Switching away from that controller to another controller will crash the app. (The initial rootViewController is also an instance of ToolbarController but that doesn't crash, only when leaving it a second time)

```
-[MyApp.MyToolbarViewController release]: message sent to deallocated instance 0x7ffe2b76be60
```

The third menu item, which links to a regular ViewController loads and unloads fine anytime.

appDelegate.swift - didFinishLaunchingWithOptions
```swift
// ...
window = UIWindow(frame: UIScreen.mainScreen().bounds)
let story = UIStoryboard(name: "Main", bundle: nil)
let mycontroller = story.instantiateViewControllerWithIdentifier("testController")
let sidebarcontroller = story.instantiateViewControllerWithIdentifier("leftSidebar")
        
window!.rootViewController = SideNavigationController(rootViewController: MyToolbarViewController(rootViewController: mycontroller), leftViewController: sidebarcontroller)
        
window!.makeKeyAndVisible()
// ...
```

LeftSidebarViewController.swift - didSelectRowAtIndexPath
```swift
// ...
let story = UIStoryboard(name: "Main", bundle: nil)
let targetVC = story.instantiateViewControllerWithIdentifier("testController")

sideNavigationController?.transitionFromRootViewController(targetVC)
// ...
```

Xcode: 7.3.1
iOS: 9.3
MK: 1.41.1

**Comment by danieldahan** [comment] 2016-05-13 16:59
I will take a look into this very soon. Thank you for submitting this.

**Comment by danieldahan** [comment] 2016-05-15 20:27
Please submit more details. Until then, I will close this issue as we cannot reproduce it. Thank you!

**Closed by danieldahan** 2016-05-15 20:27 UTC
Labels: help wanted
