### ISSUE TITLE
Button border with edge insets problem

### ISSUE THREAD

**Issue by okankocyigit** [CosmicMind/Material#571] opened 2016-10-27 15:15 UTC
If we have a border set on a button that also has content insets, borders ignore insets.

**Comment by okankocyigit** [comment] 2016-10-27 15:21
It was because i did not set class as Button with Material module, this problem is about default button border property. After I set class it worked.

**Comment by danieldahan** [comment] 2016-10-27 19:07
awesome! :)

**Comment by okankocyigit** [comment] 2016-10-31 15:58
@danieldahan I've faced this problem again, could you please check if I'm doing something wrong?

![ekran resmi 2016-10-31 18 54 09](https://cloud.githubusercontent.com/assets/16730661/19860981/7fffcafe-9f93-11e6-80d5-ff321d02b6ab.png)
![ekran resmi 2016-10-31 18 54 34](https://cloud.githubusercontent.com/assets/16730661/19860984/800246ee-9f93-11e6-9bfd-5a1d3b304ee1.png)
![ekran resmi 2016-10-31 18 54 45](https://cloud.githubusercontent.com/assets/16730661/19860983/8006ae14-9f93-11e6-8765-f5e6c4045b6f.png)
![simulator screen shot 31 eki 2016 18 53 33](https://cloud.githubusercontent.com/assets/16730661/19860982/80026f02-9f93-11e6-9bf4-6fc642641e90.png)

**Comment by danieldahan** [comment] 2016-10-31 16:52
So I believe I know what the issue is. When the Button is initialized, it removed the insets on initialization. You are using Storyboards, and Storyboards freeze dries the initialization and executes at a different time. I will make an adjustment to correct this. Would you be able to test development to see if the solution works for you?

**Comment by danieldahan** [comment] 2016-10-31 16:58
Yes, please try the `development` branch.

**Comment by okankocyigit** [comment] 2016-10-31 19:51
yes, this issue fixed in development brach. it's working thanks.

**Comment by danieldahan** [comment] 2016-10-31 19:52
Great! I will push the fix with the nest release :) Thank you

**Comment by danieldahan** [comment] 2016-11-01 04:09
This is now in master and released in [Material 2.3.0](https://github.com/CosmicMind/Material/releases/tag/2.3.0). Thank you for pointing this issue out.

**Closed by danieldahan** 2016-11-01 04:09 UTC
Labels: help wanted
