### ISSUE TITLE
CaptureView bug

### ISSUE THREAD

**Issue by VNadygin** [CosmicMind/Material#218] opened 2016-03-12 01:56 UTC
I don't know why, but I found strange behave of the CaptureView. Some times then it appear it rotate left or right... Someone know how to fix it?

**Comment by danieldahan** [comment] 2016-03-12 02:05
Can you explain your issue a little better? It is unclear to me. Thank you!

**Comment by VNadygin** [comment] 2016-03-12 02:19
so when i hold my phone at about 30 degrees tilt to the left or right and press to open CaptureView, then the camera glitches and rotates the image by 90 degrees - so everything horizontal becomes vertical and vice versa. Now the saved image then turns back to being normal.

**Comment by danieldahan** [comment] 2016-03-12 02:23
Hmmm... There are two rotations that happen in the camera. There is the rotation of the preview, which will adjust as you rotate your camera, and then there is the rotation of the view controller, which will adjust when you rotate the device. It sounds like you want to stop the rotation of the view controller. Is that correct?

**Comment by VNadygin** [comment] 2016-03-12 04:02
I want to prevent this: 
![img_1726](https://cloud.githubusercontent.com/assets/12998927/13720681/f78a1300-e7c3-11e5-9041-a97c89b8c7c4.PNG)
![img_1727](https://cloud.githubusercontent.com/assets/12998927/13720682/f78d27a2-e7c3-11e5-90a8-37bde3e24a54.PNG)

**Comment by danieldahan** [comment] 2016-03-12 19:49
That is weird, it looks like the photo is in the opposite direction from the perspective. That is an issue. Can you describe your setup and we can fix this. Thank you!

**Comment by danieldahan** [comment] 2016-03-14 05:52
I am closing this issue as I cannot reproduce it and I have not heard from you. Please feel free to reopen this issue or create a new one. Thank you!

**Comment by AhmettKeskin** [comment] 2016-06-20 07:46
Hey Daniel, i figured out smth. like this issue. My app orientation is full portrait but you set videoOrientation with UIDevice orientation. So even my app is portrait because of device orientation, sometimes captureView orientation would be landscape. And occurs a weird view

I dont know even its an issue i mean it's nature usage of camera should be what u did. But like my apps if app force one orientation, this could be problem.

i fixed this with forcing device orientation portrait. 

```
let value = UIInterfaceOrientation.Portrait.rawValue
UIDevice.currentDevice().setValue(value,` forKey: "orientation")
```

**Comment by danieldahan** [comment] 2016-06-20 12:11
Yes! I found that issue as well. I will make a fix. Where did you place that line of code?

**Comment by AhmettKeskin** [comment] 2016-06-20 13:19
I placed it in viewDidLoad where i used captureView. It was a quick solution but i can not be sure its good one :/

**Comment by danieldahan** [comment] 2016-06-20 13:22
No worries, I have been meaning to revisit the entire capture view , so I will take this as a queue to do so :)

**Comment by danieldahan** [comment] 2016-07-06 05:51
Hey! I will be looking at this tomorrow. Thank you and sorry for any delays.

**Comment by TeplrGuy** [comment] 2016-07-13 22:51
Will be waiting for the update! Thanks for the framework! Its all over Teplr

**Comment by danieldahan** [comment] 2016-07-13 23:03
Hey! I am working on Capture this week and weekend. So you should have the update soon, btw, I am updating everything for Swift 2.3 and 3.0 for Material 2. Just incase you are planning on how to integrate the new work. Also, what is Teplr? I am looking online?

**Comment by TeplrGuy** [comment] 2016-07-16 12:21
Thank you, I will be waiting for the update. Probably will not update until Teplr is ready for lunch. Teplr is a social calendar that helps you stay connected with the events and people you truly care about. As we are going into Beta, we found ourself saving lots of time because of your amazing framework. You should sign up for Beta @(teplr.co) to see how we utilized your framework. Will also be mentioning you and your framework. Thanks again!

**Comment by danieldahan** [comment] 2016-07-16 15:16
Very cool :) looking forward to seeing it. @teplrguy

**Comment by AhmettKeskin** [comment] 2016-07-16 15:34
Hey Daniel, can i mention one more issue that i figure out. When i take photo from the top ( imagine like taking pics of paper which on the desk from top ), photos turn 90 degree when i show them on imageView. ( i was careful about orientation and i'm pretty sure its portrait but image was landscape ). Could you please try this scenario ? 

We r waiting for the update also. 

Thanks a lot !

**Comment by danieldahan** [comment] 2016-07-16 17:59
@AhmettKeskin Yeah no worries, I am happy you brought this up. So basically, there is an orientation issue when first loading. I will take a look at that as I am fixing all Capture issues first. I anticipate I should have something for you to use within the latest couple days. That said, all the updates I am doing are in the development branch. Once I isolate the issue, I will make a hotfix, or suggest the fix that you can make.

**Comment by danieldahan** [comment] 2016-07-29 19:17
Hi @AhmettKeskin I haven't had a chance to suggest anything for you. Sorry about that. I am focusing on the updates for Material 2. I am going to move this issue to the Material 2 development as I am completely updating the Capture logic and setup.

**Closed by danieldahan** 2016-07-29 19:17 UTC
Labels: help wanted, question
