### ISSUE TITLE
BottomNavigationController onViewDidLoad() called twice

### ISSUE THREAD

**Issue by lancevalour** [CosmicMind/Material#378] opened 2016-05-13 20:47 UTC
When I inherit BottomNavigationController and open my view controller, viewDidLoad() function is called twice. Below is the code:
```swift
class MainViewController: BottomNavigationController {
    override func viewDidLoad() {
        super.viewDidLoad()
        print("MainViewController view did load")
    }

    override func viewDidAppear(animated: Bool) {
        print("MainViewController view did appear")
    }
}
```

Output is:
```
MainViewController view did load
MainViewController view did load
MainViewController view did appear
```

**Comment by danieldahan** [comment] 2016-05-13 20:49
There is nothing in the BottomNavigationController that executes the viewDidLoad method directly. This is interesting. How are you invoking MainViewController? Storyboards?

**Comment by lancevalour** [comment] 2016-05-13 20:51
I call presentViewController from another view controller:
```swift
 let viewController: UIViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("main") as UIViewController
 self.presentViewController(viewController, animated: true, completion: nil)
```

**Comment by danieldahan** [comment] 2016-05-13 20:52
Can you confirm that this does not happen when you are not using the BottomNav?

**Comment by lancevalour** [comment] 2016-05-13 20:54
Yes, when I use UITabBarController, onViewDidLoad() is called once.

**Comment by danieldahan** [comment] 2016-05-13 21:00
I tried to reproduce it programmatically. I wasn't able to. This is probably a side-affect of the freeze dry principal with Storyboards. Do you mind sending me a sample project, to support@cosmicmind.io. I can take a look there.

**Comment by lancevalour** [comment] 2016-05-13 21:19
Just sent it to you.

**Comment by danieldahan** [comment] 2016-05-13 21:20
Cool I will take a look. Thank you!

**Comment by danieldahan** [comment] 2016-05-13 21:31
So if you comment out the code and do this

```swift

    func onButtonClicked(){
//        let viewController: UIViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("main") as UIViewController
		
        self.presentViewController(MainViewController(), animated: true, completion: nil)
    }
```
The issue is gone. So my thinking is correct. Are familiar with how Storyboards are handled?

**Comment by lancevalour** [comment] 2016-05-13 21:48
Ok, so viewDidLoad() is called once, but I can't change the tabbar background color, it is always white.

**Comment by danieldahan** [comment] 2016-05-13 22:09
In the setup do,

```swift
bottomNavigationController.tabBar.backgroundColor = MaterialColor.grey.darken4
```

or if you subclass it, 

do

```swift
tabBar.backgroundColor = MaterialColor.grey.darken4
```

**Comment by lancevalour** [comment] 2016-05-14 17:33
I do tabBar.backgroundColor = MaterialColor.grey.darken4 in the viewDidLoad() and nothing happens. However, if I put it in viewDidAppear(), the color is changed.

It works when I use UITabbarController. Can you that in the sample code?

**Comment by mohpor** [comment] 2016-05-15 11:54
It's always safer to update UI elements in `viewDid[will]Appear()`, especially when they've been designed in IB.
@lancevalour Is it still an issue? Can we close this issue?

**Comment by lancevalour** [comment] 2016-05-15 12:26
Yes, you can close it now. Thanks.

2016年5月15日星期日，M. Porooshani <notifications@github.com> 写道：

**Closed** 2016-05-15 20:25 UTC
Labels: help wanted

**Comment by teodorpenkov** [comment] 2017-12-27 10:51
@danieldahan can you please explain the issue with the storyboards?

**Comment by danieldahan** [comment] 2017-12-27 17:55
@teodorpenkov Are you facing a similar issue?

**Comment by teodorpenkov** [comment] 2017-12-27 18:03
Hey @danieldahan , nope, I'm facing "Unbalanced calls to begin/end appearance transitions for ..." which I think is caused by Material and when I was searching through the issues of the library I found this thread and got me curious what is the problem that you described. I'm also using storyboards + swinject and I kind of like that way so I don't want to ditch storyboards...

**Comment by danieldahan** [comment] 2017-12-27 18:05
@teodorpenkov Can you confirm the issue happens in isolation? I would need to see your setup to further investigate.

**Comment by teodorpenkov** [comment] 2017-12-27 18:07
I will try to create a simple project with only Material to see if it happens and I will let you know. Can you please explain "freeze dry principal with Storyboards" or at least give me a link to find more info about it? Thanks.

**Comment by danieldahan** [comment] 2017-12-27 18:16
@teodorpenkov The simple version is that when you create instance variables attached to views, storyboards store their state for later use. This could cause issue when combining storyboards and programmatic view controllers. I don't use storyboards, so I am not the best to elaborate on them. If there is a specific issue, I investigate it and go from there.
