### ISSUE TITLE
MaterialButton > Still receiving user touches when hidden

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#249] opened 2016-03-23 00:29 UTC
Hey guys, I use a materialButton for login, which I hide once the user has successfully login, but I notice that while the button has disappear, it stills receives touchesEnded() and acts as if it was still visible.

those are the functions that are still being called when the MaterialButton is set to hidden:

```
	public override func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {
		super.touchesBegan(touches, withEvent: event)
		let duration: NSTimeInterval = MaterialAnimation.pulseDuration(width)
		
		if pulseFocus {
			pulseLayer = CAShapeLayer()
		}
		
		if let v: UIColor = pulseColor {
			MaterialAnimation.pulseAnimation(layer, visualLayer: visualLayer, color: v.colorWithAlphaComponent(pulseOpacity), point: layer.convertPoint(touches.first!.locationInView(self), fromLayer: layer), width: width, height: height, duration: duration, pulseLayer: pulseLayer)
		}
		
		if pulseScale {
			MaterialAnimation.expandAnimation(layer, scale: 1.05, duration: duration)
		}
	}
```
and:

```
	public override func touchesEnded(touches: Set<UITouch>, withEvent event: UIEvent?) {
		super.touchesEnded(touches, withEvent: event)
		MaterialAnimation.shrinkAnimation(layer, width: width, duration: MaterialAnimation.pulseDuration(width), pulseLayer: pulseLayer)
	}
```

Could you guys update the behavior so that it doesn't happen?

**Comment by danieldahan** [comment] 2016-03-23 00:31
Yeah, we will look into this :)

**Comment by GreyEcologist** [comment] 2016-03-23 00:33
Thanks! Also, I should have mentioned that the context is that I am using a MenuView which contains two FabButtons.

**Comment by danieldahan** [comment] 2016-03-23 00:34
Ah... okay, that will be helpful.

**Comment by GreyEcologist** [comment] 2016-03-29 02:32
I found a workaround, so I'll close this.

**Comment by danieldahan** [comment] 2016-03-29 02:33
What was it?

**Comment by GreyEcologist** [comment] 2016-04-21 23:32
Sorry didn't see the question, I hide the button and use removeTarget() on the method I had associated via addTarget(). The issue with that workaround is that even when hidden the button target area still prevents any user interaction, i.e in my case the button covers a table cell view and clicking in the area when the button was doesn't register events.

```
    func hideSocialButton(menuView: MenuView) {
        menuView.menu.close()
        menuView.hidden = true
        let first: MaterialButton? = menuView.menu.views?.first as? MaterialButton
        first!.removeTarget(controller, action: #selector(self.handleMenu(_:)), forControlEvents: .TouchUpInside)
    }
```

**Comment by GreyEcologist** [comment] 2016-04-29 06:36
Hey @danieldahan I know you have a lot of issues pending, but is there anything I can do to help fix this one?

**Comment by danieldahan** [comment] 2016-04-29 06:42
@GreyEcologist Hey, I am about to sign off, if you would like to try and fix this, that would be great. There are a bunch of issues, but they all relate in groupings, which will help when tackling them. The best bet to help tackle this issue, is to send a sample project illustrating the issue to support@cosmicmind.io. That would be much appreciated :)

**Comment by GreyEcologist** [comment] 2016-04-30 02:16
@danieldahan Hey Dan, I sent a sample project reproducing the issue, please let me know when you had a chance to take a look.

**Comment by mohpor** [comment] 2016-05-11 03:53
What's the status on this issue @danieldahan, @GreyEcologist ?

**Comment by danieldahan** [comment] 2016-05-11 17:47
@mohpor There is a project passed to support for this. I will forward it to you to review.

**Comment by mohpor** [comment] 2016-05-11 18:52
I'm on it now.

**Comment by mohpor** [comment] 2016-05-11 19:37
I found the root cause for this problem and designed a quick patch for it.

The culprit is the `hitTest(_:, withEvent:):` function in `menuView`. It needs to test the hit for the off shore buttons and because the menuView button is getting hidden (not disabled or removed) it still receives the touch events regardless of its visibility (because hit test only uses point-in-rect, and not actual ray-collision method).

### Solution 

Could be either:

* Redesigning the MenuView to not rely on hit test
* Add this line of code at the beginning of the hit test method:
```swift
if self.hidden {
    return nil
   }
```

Should I make a PR for second approach?

**Comment by danieldahan** [comment] 2016-05-11 19:39
@mohpor nice. Yes, please make a PR to solve the issue and please make a card for reworking the menu in Trello :) Excellent work.

**Comment by danieldahan** [comment] 2016-05-11 19:41
actually rather than return nil, if the statement doesn't have a return type, use

```swift
if !hidden {
// do something
}
/// continues and ignores work. 
```

Also no need for `self`, unless in a closure with `unowned` or `weak`

**Comment by danieldahan** [comment] 2016-05-11 20:05
I am closing this issue as it will be released in the next release later tonight. Thank you @mohpor

**Closed by danieldahan** 2016-05-11 20:05 UTC
Labels: help wanted, question

**Comment by GreyEcologist** [comment] 2016-05-13 16:02
Sorry... late to the party! Thanks guys!
