### ISSUE TITLE
SideNavigationController gestures in conflict with the rootViewController subview gestures

### ISSUE THREAD

**Issue by xaviermawet** [CosmicMind/Material#322] opened 2016-04-19 10:13 UTC
Hi,

I've a NavigationController as the rootViewController of a SideNavigationController. The embedded ViewController of the NavigationController has a document viewer/editor (PSPDFKit) as a subview. This subview (the document editor) requires tap gestures and pan gestures for annotations. But the gestures require by the document editor are "hidden" by the SideNavigationController gestures.

I've the same issue (behavior) after having disabled the left and right view with the enabled properties :
```swift
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    sideNavigationController?.enabled = false
}

override func viewWillDisappear(animated: Bool) {
    super.viewWillDisappear(animated)
    sideNavigationController?.enabled = true
}
```

Is there an other way to disable gestures for a sideNavigationController ?
Or make the functions `prepareGestures()` and `removeGestures()` public ?

Thanks for all you did

**Comment by danieldahan** [comment] 2016-04-19 11:26
I will be revisiting the pan gestures later today. Let me see what is possible :)

**Comment by havocked** [comment] 2016-04-26 11:25
By the way it seems that `SideNavigationController`'s swipe gesture (for leftView) on `rootViewController` override the "swipe to delete" gesture, if the `rootViewController` is a `UITableViewController` that implements "swipe to delete" feature

**Comment by Bashta** [comment] 2016-05-03 05:17
the problem is common also with UIControl subclasses. An easy solution is to make the remove/add gesture recognisers public. Dirty but works until the maintainer fixes the issue.

**Comment by mohpor** [comment] 2016-05-03 05:18
@Bashta 
@danieldahan has fixed the issue and will be released soon.

**Comment by Bashta** [comment] 2016-05-03 05:23
Nice! Is there a branch with the fix already available?

**Comment by mohpor** [comment] 2016-05-03 05:26
I'm afraid not.
But if you want to live on the edge and enjoy the development with others, you can always use the `development` branch and participate in the [Gitter Room](https://gitter.im/CosmicMind/Material)'s chat.

**Comment by Bashta** [comment] 2016-05-03 05:27
+1 to karma +3 to friendship

**Comment by danieldahan** [comment] 2016-05-03 22:38
@xaviermawet Please try 1.40.0 and let me know if the issue is fixed. I am closing the issue for now, please reopen or create a new one if the issue persists.

**Closed by danieldahan** 2016-05-03 22:38 UTC
Labels: help wanted

**Comment by xaviermawet** [comment] 2016-05-04 07:35
That works like a charms :D Thanks for all you did

**Comment by havocked** [comment] 2016-05-04 07:59
Yeah works really well!

Did you reduce the threshold, it seems that it more difficult to get the swipe the sideView.

But it is really ok though ! 👍

**Comment by danieldahan** [comment] 2016-05-04 17:04
@havocked awesome. Yes I lowered it so it wouldn't be so far out. Maybe it is too little. To adjust the value, you can set rightThreshold, and leftThreshold on the SideNavigationController instance. 

```swift
override func viewWillAppear(animated: Bool) {
		super.viewWillAppear(animated)
sideNavigationController?.leftThreshold = 64
sideNavigationController?.rightThreshold = 64
}
```

If you find a better value to use as the default, please let me know.
