### ISSUE TITLE
App freezes when textfield scrolls horizontally in secure entry mode.

### ISSUE THREAD

**Issue by azizuysal** [CosmicMind/Material#626] opened 2016-12-08 00:28 UTC
I did some tests and I can easily reproduce this. Just set font size to anything above 17 and set secure text entry on, and it will happen every single time when you enter more chars than visible and the field tries to scroll horizontally. I tested with both UIFont.systemFont(ofSize: 20) and RobotoFont.regular(with: 20) with identical results in a test project. If you cannot reproduce, I can send you a test project.

**Comment by danieldahan** [comment] 2016-12-08 19:32
Cool, I will be looking at this tonight :)

**Comment by danieldahan** [comment] 2016-12-09 10:38
@azizuysal Hey, I opened the [TextField sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/TextField). I wasn't able to reproduce this. If you don't mind sending a sample to support@cosmicmind.com, that would be very helpful. Also, what version of Material are you running?

**Comment by azizuysal** [comment] 2016-12-13 20:11
I sent you a sample project and I've made a few more tests, and here are my observations:
1. This happens only when adjustsFontSizeToFitWidth is set to true along with secure text entry mode, and font size above 17. And when testing with Xcode 8.2 iOS 10.2, I noticed it doesn't happen anymore, so this may be an iOS bug. Try running the sample project in both iOS 10.1 and 10.2.
2. In Xcode 8.2, if I set the font size to a big number like 40, and when adjustsFontSizeToFitWidth is false, text does not scroll horizontally at all, and typed chars cannot be seen anymore. Again, as this does not happen in Xcode 8.1/iOS 10.1, so this may also be an iOS bug.
3. Not a bug maybe, but when more text than would fit in textfield is typed, and then focus is shifted to elsewhere, three dots (...) is appended to text, which doesn't seem right for username/password fields and looks a bit odd. I think this should be optional.

**Comment by danieldahan** [comment] 2016-12-13 20:13
@azizuysal thank you for sending the sample. I will be out tonight and tomorrow, so I will take a look within the next couple days. I need to do an update for Xcode 8.2 and run a full test against Material. So this is good insight and I appreciate it.

**Comment by danieldahan** [comment] 2016-12-16 17:42
Hey, So I ran an experiment. I made a new `UITextField` and then set the size to 40 with Roboto font. All worked correctly. Then I switched the `UITextField` to a `Material.TextField` and all still worked correctly. I didn't add any constraints and such, kept it at the default. In Material there isn't any modifications to the `UITextField` itself that should cause this. Everything else is added around the `UITextField`. I have attached images for my experiment. I looked online and found similar issues to yours that were caused by AutoLayout constraints. I am going to close this issue and invite you to chat with me at [Material Gitter](https://gitter.im/CosmicMind/Material) to help solve your problem. I am closing the issue because it is not a direct problem with Material. All the best and I look forward to chatting with you :)

<img width="1186" alt="screen shot 2016-12-16 at 11 36 32 am" src="https://cloud.githubusercontent.com/assets/9982123/21272322/5c452e0a-c384-11e6-9722-6a26db91eafa.png">
<img width="1190" alt="screen shot 2016-12-16 at 11 36 41 am" src="https://cloud.githubusercontent.com/assets/9982123/21272323/5c4ef016-c384-11e6-9917-726c2124d545.png">
<img width="1182" alt="screen shot 2016-12-16 at 11 36 51 am" src="https://cloud.githubusercontent.com/assets/9982123/21272324/5c5617a6-c384-11e6-93a7-43850c70aec0.png">

**Closed by danieldahan** 2016-12-16 17:42 UTC
Labels: bug, investigate
