### ISSUE TITLE
MaterialSwitch breaks tableview 

### ISSUE THREAD

**Issue by jeandavid** [CosmicMind/Material#399] opened 2016-05-25 13:27 UTC
I have a paginated tableview. Each cell includes a MaterialSwitch. 
When I fetch more items from the server and appends them to previously 
loaded items, tableView.reload() breaks. 

It complains about func animateToState(...) in the MaterialSwitch class. See screenshot. 

<img width="1414" alt="screen shot 2016-05-25 at 4 20 52 pm" src="https://cloud.githubusercontent.com/assets/3328783/15541506/7891edcc-2295-11e6-95d8-5aae18909179.png">

**Comment by mohpor** [comment] 2016-05-25 13:45
@jeandavid do you have a global Exception breakpoint? if so, could you disable it for now to see what's causing this to break?

**Comment by jeandavid** [comment] 2016-05-25 13:55
@mohpor I have removed all breakpoints. It breaks here: 

<img width="1426" alt="screen shot 2016-05-25 at 4 52 23 pm" src="https://cloud.githubusercontent.com/assets/3328783/15542432/6fa8ba52-2299-11e6-8f20-bd4a6de1959b.png">

**Comment by mohpor** [comment] 2016-05-25 13:59
I guess I know what's causing this. I will investigate some more and get back to you ASAP. Thanks for reporting this.

**Comment by danieldahan** [comment] 2016-05-25 16:35
I believe the issue is the unowned self, this should be moved to a weak reference. Thank you, we will make the change.

**Comment by danieldahan** [comment] 2016-05-26 19:08
This is now fixed in release 1.41.3, and is being release today. I will close this issue when it is released.

**Comment by danieldahan** [comment] 2016-05-26 19:34
released [1.41.3](https://github.com/CosmicMind/Material/releases/tag/1.41.3)

**Closed by danieldahan** 2016-05-26 19:34 UTC
Labels: bug
