### ISSUE TITLE
Center detail label in CardView

### ISSUE THREAD

**Issue by egfconnor** [CosmicMind/Material#440] opened 2016-06-15 00:41 UTC
I have a CardView that I am setting a title to and also a detail view. The title is fine being centered with NSTextAlignment.Center but I need the detail label to be centered by sizing the UILabel to fit it's contents, and then centering it's whole view inside the CardView horizontally while still being left justified.

My code currently is:

        let cardView: CardView = CardView()
        cardView.divider = false

        let titleLabel: UILabel = UILabel()
        titleLabel.text = title
        titleLabel.textAlignment = NSTextAlignment.Center
        titleLabel.numberOfLines = 0
        titleLabel.textColor = MaterialColor.black
        titleLabel.font = MaterialFont.systemFontWithSize(20)

        cardView.titleLabel = titleLabel

        let detailLabel: UILabel = UILabel()
        detailLabel.text = detail
        detailLabel.textColor = MaterialColor.grey.darken2
        detailLabel.numberOfLines = 0

        cardView.contentView = detailLabel

How would I accomplish this? Thanks!

**Comment by danieldahan** [comment] 2016-06-15 19:10
Hi, 

You could make a container view and add that to the cardView.contentView. That container view will be dynamically sized by the cardView. Within there you can do what you like. So sizing the label can be done however you please. 

Let me know if that works for you :)

**Comment by egfconnor** [comment] 2016-06-15 19:12
@danieldahan alright I had tried that but ran into issues with the container view overflowing outside the CardView's bounds and couldn't figure out how to solve that. I'm a little new to iOS's layout system so I probably should just go do some reading.

**Comment by danieldahan** [comment] 2016-06-15 19:16
Have you seen this [example](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/CardView) project, and this snippet in particular?

```swift
let cardView: CardView = CardView()
		
// Title label.
let titleLabel: UILabel = UILabel()
titleLabel.text = "Welcome Back!"
titleLabel.textColor = MaterialColor.blue.darken1
titleLabel.font = RobotoFont.mediumWithSize(20)
cardView.titleLabel = titleLabel
		
// Detail label.
let detailLabel: UILabel = UILabel()
detailLabel.text = "It’s been a while, have you read any new books lately?"
detailLabel.numberOfLines = 0
cardView.contentView = detailLabel
```

Also, read up on this, [Layout](http://www.cosmicmind.io/material/layout), which will make the layout system so much easier for you in iOS.

**Comment by danieldahan** [comment] 2016-06-15 19:19
I think that part of the issue is in how you are adding the cardView. If you would like, send me a sample project to support@cosmicmind.io and I will see if I can help you from there.

**Comment by egfconnor** [comment] 2016-06-15 19:30
@danieldahan thank you very much. I'll work on getting you that either tonight or tomorrow.

**Comment by danieldahan** [comment] 2016-06-15 19:39
Cool, I will close this issue then, and after you send it, follow up here on [Gitter](https://gitter.im/CosmicMind/Material). Thanks :)

**Closed by danieldahan** 2016-06-15 19:39 UTC
Labels: help wanted
